config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [ :registrations, :sessions ]
  as :user do
    get '/login' => 'devise/sessions#new', :as => :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    get '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get '/register' => 'couples#new', as: :new_couple_registration
    post '/register' => 'couples#create', as: :couple_registration
  end

  resources :stories, except: [ 'index' ]
  resources :couples, only: [ :show, :edit, :update ]

  namespace :home do
    get :index
  end

  post '/upload_images' => 'home#upload_images'

  root to: 'home#index'
end

app/models/couple.rb
class Couple < ActiveRecord::Base
  devise :registerable

  belongs_to :he, class_name: "User", foreign_key: :his_id
  belongs_to :she, class_name: "User", foreign_key: :her_id

  alias_attribute :his, :he
  alias_attribute :her, :she

  has_many :stories

  has_one :photo, as: :imageable

  validates :he, presence: true
  validates :she, presence: true

  def name
    "#{ he.name } and #{ she.name }"
  end

  def avatar(image_size = :thumb)
    self.photo.image.url image_size if self.photo.present?
  end
end

app/controllers/couples_controller.rb
class CouplesController < ApplicationController
  layout 'couples', except: [ :new, :edit ]
  layout 'couple_sign_up', only: [ :new, :edit ]

  def new
    @couple = Couple.new
  end

  def create
    @couple = Couple.new
    @he = User.new his_params
    @she = User.new her_params

    @user_to_log_in = (rand(100) > 50) ? @he : @she

    @couple.photo = Photo.find_by(id: their_photo_param)
    @he.photo = Photo.find_by(id: his_photo_param)
    @she.photo = Photo.find_by(id: her_photo_param)

    if @couple.photo
      @couple.photo.update couple_photo_params
    end

    if @he.save and @she.save and @couple.he = @he and @couple.she = @she and @couple.save
      sign_in(User, @user_to_log_in)
      redirect_to couple_path(@couple)
    else
      render "new"
    end
  end

  def edit
    @couple = Couple.find(params[:id])
  end

  def update
    # required for settings form to submit when password is left blank
    if params[:his][:password].blank? && params[:his][:password_confirmation].blank?
      params[:his].delete(:password)
      params[:his].delete(:password_confirmation)
    end

    if params[:her][:password].blank? && params[:her][:password_confirmation].blank?
      params[:her].delete(:password)
      params[:her].delete(:password_confirmation)
    end

    @user = current_user
    @couple = Couple.find(params[:id])
    @he = @couple.he
    @she = @couple.she

    if params[:his][:photo_id].present?
      @he.photo = Photo.find(params[:his][:photo_id])
      params[:his].delete :photo_id
    end

    if params[:her][:photo_id].present?
      @she.photo = Photo.find(params[:her][:photo_id])
      params[:her].delete :photo_id
    end

    if params[:their][:photo_id].present?
      @couple.photo = Photo.find(params[:their][:photo_id])
      params[:their].delete :photo_id
    end

    if @couple.photo
      @couple.photo.update couple_photo_params
    end

    @he.update_attributes his_params
    @she.update_attributes her_params

    if @he.save and @she.save and @couple.save
      # Sign in the user bypassing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to couple_path(@couple), { flash: { notice: 'Your settings are saved' } }
    else
      render "edit"
    end
  end

  def show
    @couple = Couple.find(params[:id])

    @tracks = @couple.stories.map do |story|
      story.present_tracks
    end.flatten(1)
  end

  protected

  def user_params
    [ :name, :email, :password, :password_confirmation ]
  end

  def his_params
    params.permit(:his => user_params)[:his]
  end

  def her_params
    params.permit(:her => user_params)[:her]
  end

  def his_photo_param
    params.permit(:his => [:photo_id])[:his][:photo_id]
  rescue
    nil
  end

  def her_photo_param
    params.permit(:her => [:photo_id])[:her][:photo_id]
  rescue
    nil
  end

  def their_photo_param
    params.permit(:their => [:photo_id])[:their][:photo_id]
  rescue
    nil
  end

  def couple_photo_params
    params.permit(:their => [:source_x, :source_y, :scale_factor])[:their]
  end

  def couple_params
    params.permit(:their => [:photo_id, :source_x, :source_y, :scale_factor])[:their]
  end

  def after_update_path_for(couple)
    couple_path(couple)
  end
end

app/helpers/couples_helper.rb
module CouplesHelper
end

app/views/couples/edit.html.erb
<script type="text/javascript">
    $(function() {
        initPhotoDroppers({
            mode: 'edit',
            photo: <%= raw @couple.avatar(:original).to_json %>,
            sourceX: <%= @couple.photo.source_x %>,
            sourceY: <%= @couple.photo.source_y %>,
            scaleFactor: <%= @couple.photo.scale_factor %>
        });
    });
</script>

<section class="bck theme landing text center padding">
  <%= form_tag(couple_path(@couple), method: 'put') do %>
    <div class="row">
      <div class="column_10 offset_1">
        <h1 class="text bold">Settings</h1>

        <h2 class="padding">
          Here you can change your settings
        </h2>

        <% if @couple.errors.present? %>
          <% @couple.errors.messages.each do |message| %>
            <div class="row error">
              <%= message %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="column_4">
        <div class="photo-dropper-wrapper">
          <div class="his photo-dropper">
            <% if @couple.his.photo.present? %>
              <img src="<%= @couple.his.avatar %>" />
            <% else %>
                <span>Drop his photo here</span>
            <% end %>
          </div>
        </div>
      </div>

      <div class="column_4">
        <div class="photo-dropper-wrapper">
          <div class="their photo-dropper">
            <% if @couple.photo.present? %>
              <img src="<%= @couple.avatar %>" />
            <% else %>
                <span>Drop your both photo</span>
            <% end %>
          </div>
        </div>
      </div>

      <div class="column_4">
        <div class="photo-dropper-wrapper">
          <div class="her photo-dropper">
            <% if @couple.her.photo.present? %>
              <img src="<%= @couple.her.avatar %>" />
            <% else %>
              <span>Drop her photo here</span>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="column_6">
        <input type="text" name="his[name]" placeholder="Name" autofocus="true" value="<%= @couple.his.name %>" />
        <input type="email" name="his[email]" placeholder="E-mail" autofocus="true" value="<%= @couple.his.email %>" />
        <input type="password" name="his[password]" placeholder="Password" autocomplete="off" />
        <input type="password" name="his[password_confirmation]" placeholder="Password, once again" autocomplete="off" />
      </div>

      <div class="column_6">
        <input type="text" name="her[name]" placeholder="Name" autofocus="true" value="<%= @couple.her.name %>" />
        <input type="email" name="her[email]" placeholder="E-mail" autofocus="true" value="<%= @couple.her.email %>" />
        <input type="password" name="her[password]" placeholder="Password" />
        <input type="password" name="her[password_confirmation]" placeholder="Password, once again" />
      </div>
    </div>

    <div class="row padding">
      <div class="column_8 text-right photo-editor">
        <canvas class="portrait-editor" width="350" height="350"></canvas>
        <input name="their[source_x]" id="their_source_x" type="hidden" />
        <input name="their[source_y]" id="their_source_y" type="hidden" />
        <input name="their[scale_factor]" id="their_scale_factor" type="hidden" />
      </div>

      <div class="column_4 text-left">
        <div id="scale-slider"></div>
      </div>
    </div>

    <div class="row padding">
      <div class="column_12 text center">
        <button type="submit" class="button">Save!</button>
      </div>
    </div>
  <% end %>
</section>

app/views/couples/new.html.erb
<script type="text/javascript">
    $(function() {
        initPhotoDroppers({
            mode: 'create'
        });
    });
</script>

<section class="bck theme landing text center padding">
  <%= form_tag(couple_registration_path(@couple), method: 'post') do %>
    <div class="row">
      <div class="column_10 offset_1">
        <h1 class="text bold">Sign up</h1>

        <h2 class="padding">
          Here you should register with your half
        </h2>

        <% if @couple.errors.present? %>
          <% @couple.errors.messages.each do |message| %>
            <div class="row error">
              <%= message %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="column_4">
        <div class="photo-dropper-wrapper">
          <div class="his photo-dropper">
            <span>Drop his photo here</span>
          </div>
        </div>
      </div>

      <div class="column_4">
        <div class="photo-dropper-wrapper">
          <div class="their photo-dropper">
            <span>Drop your both photo</span>
          </div>
        </div>
      </div>

      <div class="column_4">
        <div class="photo-dropper-wrapper">
          <div class="her photo-dropper">
            <span>Drop her photo here</span>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="column_6">
        <input type="text" name="his[name]" placeholder="Name" autofocus="true" />
        <input type="email" name="his[email]" placeholder="E-mail" autofocus="true" />
        <input type="password" name="his[password]" placeholder="Password" autocomplete="off" />
        <input type="password" name="his[password_confirmation]" placeholder="Password, once again" autocomplete="off" />
      </div>

      <div class="column_6">
        <input type="text" name="her[name]" placeholder="Name" autofocus="true" />
        <input type="email" name="her[email]" placeholder="E-mail" autofocus="true" />
        <input type="password" name="her[password]" placeholder="Password" />
        <input type="password" name="her[password_confirmation]" placeholder="Password, once again" />
      </div>
    </div>

    <div class="row padding">
      <div class="column_8 text-right photo-editor">
        <canvas class="portrait-editor" width="350" height="350"></canvas>
        <input name="their[source_x]" id="their_source_x" type="hidden" />
        <input name="their[source_y]" id="their_source_y" type="hidden" />
        <input name="their[scale_factor]" id="their_scale_factor" type="hidden" />
      </div>

      <div class="column_4 text-left">
        <div id="scale-slider"></div>
      </div>
    </div>

    <div class="row padding">
      <div class="column_12 text center">
        <button type="submit" class="button">Sign up!</button>
      </div>
    </div>
  <% end %>
</section>

app/views/couples/show.html.erb
<script type="text/javascript">
  window.tracks = <%= raw @tracks.to_json %>;

  window.onload = function() {
      initMap();

      setupPortrait({
          photo: <%= raw @couple.avatar(:original).to_json %>,
          sourceX: <%= @couple.photo.source_x %>,
          sourceY: <%= @couple.photo.source_y %>,
          scaleFactor: <%= @couple.photo.scale_factor %>
      });

      showTracks();

      [].forEach.call(document.querySelectorAll('.list-group-item'), function(elt, idx) {
          elt.addEventListener('mousemove', function() {
              centerTrack(idx);
          });
      });
  };
</script>

<div class="bck middle text center couple-header">
  <div class="row">
    <div class="column_12 text-center">
      <h1>Hello!</h1>
    </div>
  </div>

  <div class="row">
    <div class="span-12 text-center">
      <canvas class="portrait-together" width="350" height="350"></canvas>
    </div>
  </div>

  <div class="row">
    <div class="column_12 text-center">
      <h2>We are <%= @couple.she.name %> and <%= @couple.he.name %></h2>
    </div>
  </div>

  <div class="row">
    <div class="column_12 text-center">
      <h1>And we are travelling!</h1>
    </div>
  </div>
</div>

<div class="bck theme">
  <% if @couple.stories.size > 0 %>
      <div class="row text-center">
        <div class="column_12">
          <h1>And here are some of our stories:</h1>
        </div>
      </div>

      <div class="row">
        <div class="column_12 text-center">
          <div id="map"></div>
        </div>
      </div>

      <div class="row">
        <div class="column_12">
          &nbsp;
        </div>
      </div>

      <div class="row">
        <div class="column_8 offset_2 story-list">
          <div class="list-group">
            <% @couple.stories.each do |story| %>
              <div class="list-group-item">
                <p class="pull-left">
                  <img class="avatar-small" src="<%= story.author.avatar || image_path(story.author.is_he? ? 'male.png' : 'female.png') %>" alt="...">
                </p>

                <h4 class="list-group-item-heading"><a href="<%= url_for story %>"><%= story.title %></a></h4>

                <% if user_signed_in? and story.couple == current_user.couple %>
                    <div class="story-actions">
                      <a href="<%= story_path(story) %>" class="button tiny warning" data-method="delete">Delete</a>
                      <a href="<%= edit_story_path(story) %>" class="button tiny">Edit</a>
                    </div>
                <% end %>

                <p class="list-group-item-text">
                  <%= raw story.short_body %>
                </p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
  <% else %>
      <div class="row text-center">
        <div class="column_12">
          <h1>But currently we can't tell you anything</h1>
        </div>
      </div>
  <% end %>
</div>