config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [ :registrations, :sessions ]
  as :user do
    get '/login' => 'devise/sessions#new', :as => :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    get '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get '/register' => 'couples#new', as: :new_couple_registration
    post '/register' => 'couples#create', as: :couple_registration
  end

  resources :stories, except: [ 'index' ]
  resources :couples, only: [ :show, :edit, :update ]

  namespace :home do
    get :index
  end

  post '/upload_images' => 'home#upload_images'

  root to: 'home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer class="bck light padding text-center">
  &copy; Artem Shoobovych, 2014 - <%= Date.today.year %>
</footer>

app/views/application/_header.html.erb
<header class="bck light padding">
  <div class="row">
    <div class="column_6">
      <h2 class="text thin">
        <a href="/" class="no-hover">
          <% if user_signed_in? %>
            <%= current_user.couple_name %>
          <% else %>
            They Are Tripping
          <% end %>
        </a>
      </h2>
    </div>

    <% if user_signed_in? %>
      <nav class="column_6 text right bold">
        <a class="button bck theme" href="<%= edit_couple_path(current_user.couple) %>">Settings</a>
        <a class="button bck green" href="<%= new_story_path %>">Write</a>
        <a class="button" href="<%= url_for :destroy_user_session %>">Sign out</a>
      </nav>
    <% else %>
      <nav class="column_6 text right bold">
        <a class="button" href="<%= url_for :new_couple_registration %>">Sign up</a>
        <a class="button bck theme" href="<%= url_for :new_user_session %>">Log in</a>
      </nav>
    <% end %>
  </div>
</header>